# For more see https://gohugo.io/content-management/menus/
main:                
  - identifier: home
    name: Home
    url: /
    weight: 1

  - identifier: search
    name: Search
    url: /search/
    weight: 5

  - identifier: posts
    name: Posts
    url: /post/
    weight: 10

  - identifier: github
    name: GitHub
    url: 'https://github.com/filipviz/'
    weight: 20
    params:
      external: true

  - identifier: twitter
    name: Twitter/X
    url: 'https://x.com/filipviz/'
    weight: 25
    params:
      external: true

feeds:
  - identifier: rss
    name: RSS
    url: /feeds/feed.rss.xml
    weight: 1
  - identifier: atom
    name: Atom
    url: /feeds/feed.atom.xml
    weight: 2
  - identifier: json
    name: Json
    url: /feeds/feed.json
    weight: 3
